### PR TITLE
Fix L0_CApi segmentation fault when using cuda (#184)

### PR DESCRIPTION
**Pull request by mc-nv**
* fix segfault while copying data to vector when using cuda memory

* Fix comments

* Update src/client_backend/triton_c_api/triton_loader.cc

---------

### CODE REVIEW

**Comment by krishung5** [comment]
Could you please run the pre-commit hook to pass the check?

**Comment by yinggeh** [comment]
Please fix pre-commit error. LGTM otherwise.

**Comment by mc-nv** [comment]
I won't run any pre-commit hooks, it's a cherry-pick.

**Comment by krishung5** [comment]
@mc-nv I think it's fine if not fixed for now, but will need to address the pre-commit hook later when advancing main to 24.11 changes later.

**Review by krishung5 — APPROVED** [review]

**Pull request merged**
