### PR TITLE
Update 'main' to track development for 0.0.9 / 24.12

### PR DESCRIPTION
**Pull request by mc-nv**

### CODE REVIEW

**Comment by fpetrini15** [comment]
@mc-nv we just updated this value last week, are you sure it's already time to track 24.12 into `main`?

**Comment by mc-nv** [comment]
> @mc-nv we just updated this value last week, are you sure it's already time to track 24.12 into `main`?

I'm following our process... see documentation.

**Review by lkomali — APPROVED** [review]

**Comment by fpetrini15** [comment]
According to the last release cycle, this value was not updated until _post_ release: https://github.com/triton-inference-server/perf_analyzer/pull/159

**Review by fpetrini15 — APPROVED** [review]
Thanks for syncing and explaining. LGTM

**Pull request merged**
